# Generated by Django 2.2.1 on 2019-05-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='serial_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
