# Generated by Django 2.2.1 on 2019-05-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190511_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
